Create App. - Feature Bundle - Dec 2020
vircadia/project-athena pull request #894
Opened 2020-12-01 05:43 UTC by AleziaKurdis

Content of this feature bundle:

**New "Tools" menu to the Create Application**

![image](https://user-images.githubusercontent.com/60075796/100700278-10b8dd00-336b-11eb-81f5-e7972193ab40.png)

The previous "**Selection**" and "**Actions**" menu has been renamed "**Select**" and "**Edit**".
We have now all the actions regrouped in the 3 menus: "**Select**", "**Edit**" and "**Tools**".

Some changes coming with this:
1- The menu "**Teleport To Selected Entities**" has been moved from the "Select" menu to the new "Tools" menu.

2- The "Hotkey" "G" is now used to toggle the grid (previously it was to align it to the selection). It was making sense to have G (for Grid) to manage the visibility of this one.

3- New "Hotkey" has been added to control the other actions related to the Grid:
 "**Activate/Deactivate Snap to Grid**" can be triggered by clicking "H"
"**Align Grid to Selected Entities**" can be triggered by clicking "J"
 "**Align Grid to Avatar**" can be triggered by clicking "K"

4- The actions: "**Align Grid to Selected Entities**" and "**Align Grid to Avatar**" will turn on the grid if it was not visible. (Doing this imply that you want to have the grid to be visible). But you will still need to do "**Toggle Grid**" (**G**) to turn the grid off.
Note that "**Align Grid to Selected Entities**" will happen only If there is at least one entity selected.

**Main "Edit" menu**

The 2 "**Import Entities**" actions have been brought back to the main "**Edit**" menu. 
(Since there was no unanimity about their removal)

A **separator** has been added to regroup the Create App's menuItems.

![image](https://user-images.githubusercontent.com/60075796/100701302-5aa2c280-336d-11eb-83c1-1446929ce9d2.png)

2020-12-01 05:47 UTC, AleziaKurdis commented
This commit is fully functional, This means that it can be tested.
But "Do Not Merge" now. 
I might add additional features in the next week.
or do readjustments depending some feedbacks?

2020-12-01 07:14 UTC, ctrlaltdavid requested changes

2020-12-01 07:14 UTC, ctrlaltdavid commented on scripts/system/create/edit.js
> +
Unwanted space char.

2020-12-01 07:14 UTC, ctrlaltdavid commented on scripts/system/create/edit.js
> +
Unwanted spaces.

2020-12-01 07:14 UTC, ctrlaltdavid commented on scripts/system/create/entityList/html/js/entityList.js
> +        elSelectTopFamily = document.getElementById("selecttopfamily");
Unwanted space.

2020-12-01 07:14 UTC, ctrlaltdavid commented on scripts/system/create/entityList/html/js/entityList.js
> +            EventBridge.emitWebEvent(JSON.stringify({ type: 'toggleSpaceMode' }));
Inconsistent use of `'` vs. `"` in this area.

2020-12-01 07:14 UTC, ctrlaltdavid commented on scripts/system/libraries/gridTool.js
> +        if (position.x === 0 && position.y === 0 && position.z === 0) {
Better to use `0.0`s, I think, to indicate that they're real numbers rather than integeters.

2020-12-01 07:20 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-31dd724_bbde93f5.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-31dd724_bbde93f5.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-31dd724.tar_bbde93f5.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-31dd724.tar_bbde93f5.gz

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-31dd724_bbde93f5.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-31dd724_bbde93f5.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Quest-Alpha-PR894-31dd724_bbde93f5.apk

2020-12-02 04:00 UTC, AleziaKurdis commented
**Grid upgrade...**
The Grid is now using a **"local" Entity** instead of a **deprecated 3d Overlay**.

2020-12-02 06:27 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-740f7dd_670d832c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-740f7dd.tar_670d832c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-740f7dd.tar_670d832c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-740f7dd_670d832c.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-740f7dd_670d832c.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-740f7dd_670d832c.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Quest-Alpha-PR894-740f7dd_670d832c.apk

2020-12-02 18:25 UTC, ctrlaltdavid approved these changes

2020-12-03 04:02 UTC, AleziaKurdis commented
You can remove the "**Do Not Merge**" tag.
That will be all for this PR.
I expected to address the Grid issues with the Local mode, but the expected behavior is far to be clear.

2020-12-04 01:33 UTC, Aitolda commented
Everything seems to be working as intended.

2020-12-04 20:55 UTC, SilverfishVR commented
PR894-740f7dd

Looks good 👍 👍  only issue I found is that the default width of the create window (in desktop) is too narrow to fit the new buttons:
![Screenshot 2020-12-04 212220](https://user-images.githubusercontent.com/53531160/101213652-fa689500-367a-11eb-817e-601e43ecf397.png)

Actually it is also too narrow for the Properties page to show properly so maybe the best solution is to just make the default wider?

2020-12-05 01:09 UTC, AleziaKurdis commented
Is this the tablet mode in Desktop?
( I would have expected this to do as in VR .. and be displayed in landscape)

2020-12-05 01:15 UTC, AleziaKurdis commented
Maybe open a bug for this. Since it was not introduced with this PR but with the previous one.

2020-12-05 04:55 UTC, AleziaKurdis commented
**Create Tools window width (in Desktop mode)...**
In desktop mode only, the default windows width is now 750px instead of 490px.
which is closer than what we have in HMD (which is landscape display)
the 2 Import buttons (only in HMD) are now one under the other, in full width.
No change in HMD.
---
Please test and let me know if this is fine.

2020-12-05 06:42 UTC, vircadia-build-notifier commented
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-2020ccc_536bf4ef.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-2020ccc.tar_536bf4ef.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-2020ccc_536bf4ef.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-2020ccc.tar_536bf4ef.gz

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Quest-Alpha-PR894-2020ccc_536bf4ef.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-2020ccc_536bf4ef.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/kasenvr_project-athena/PR894/Vircadia-Alpha-PR894-2020ccc_536bf4ef.exe

2020-12-05 18:28 UTC, SilverfishVR commented
looks good to me, mind you, that's on a UWQHD monitor but as long as it fits in a full HD monitor (so you can resize it) I thinks it's good

2020-12-05 20:25 UTC, ctrlaltdavid approved these changes

2020-12-10 22:54 UTC, merged